export const pageLinks = [
  { href: "/accordion", label: "Accordion Challenge", category: "components" },
  { href: "/counter", label: "Counter Challenge", category: "components" },
  { href: "/fetch-display-data", label: "Fetch and Display Data Challenge", category: "components" },
  { href: "/mini-task-manager", label: "Mini Task Manager Challenge", category: "components" },
  { href: "/custom-hook", label: "Custom Hook Challenge", category: "hooks" },
  { href: "/todo-list", label: "To-Do List Challenge", category: "components" },
  { href: "/user-search-filter", label: "User Search Filter Challenge", category: "components" },
  { href: "/quiz-app", label: "Quiz App Challenge", category: "components" },
  { href: "/shopping-cart", label: "Shopping Cart Challenge", category: "components" },
  { href: "/pagination", label: "Pagination Challenge", category: "components" },
  { href: "/pagination-search", label: "Pagination with Search Challenge", category: "components" },
  { href: "/form-validation-zod", label: "Form Validation with Zod Challenge", category: "components" },
  { href: "/use-memo", label: "useMemo Challenge", category: "hooks" },
  { href: '/use-reducer', label: "useReducer Challenge", category: "hooks" },
  { href: "/use-ref", label: "useRef Challenge", category: "hooks" },
  { href: "/redux-state-management", label: "Redux State Management Challenge", category: "state-management" },
];
